version: "3.9"

volumes:
  postgres_data:

services:
  db:
    image: postgres:16
    container_name: task_manager_db
    restart: always
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: task_manager_web
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://task_user:strong_password@db:5432/task_manager
    depends_on:
      - db
    volumes:
      - .:/app
