"""empty message

Revision ID: 235bad293495
Revises: d6bbbc115c6f
Create Date: 2026-03-04 16:51:08.374109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235bad293495'
down_revision = 'd6bbbc115c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
